#!/bin/bash
today=$(date +"%Y-%m-%d")

/home/ubuntu/miniconda3/envs/snakemake/bin/python3 /home/ubuntu/ccgp-data-wrangling/update_gsheet.py &>> /home/ubuntu/ccgp-data-wrangling/logs/update_gsheet/${today}_log.txt