#!/bin/bash
today=$(date +"%Y-%m-%d")
export GOOGLE_APPLICATION_CREDENTIALS=/mnt/ccgp-data-wrangling/google_secret.json
/home/ubuntu/miniconda3/envs/snakemake/bin/python3 /home/ubuntu/ccgp-data-wrangling/update_metadata.py metadata &>> /home/ubuntu/ccgp-data-wrangling/logs/update_metadata/${today}_log.txt